justeat/f-footer

.travis.yml, CHANGELOG.md, _build/config.js, gulpfile.js, package.json, src/scss/index.scss, src/scss/partials/_siteSelector.scss, yarn.lock
- Added footer styles
- Updated package dependencies.
=> Added footer styles.

src/scss/index.scss
=> Updated chevron rotation styles.

CHANGELOG.md, package.json, yarn.lock
- Moved build packages in `devDependencies`.
- Upgraded `gulp-build-fozzie` package.
=> Updated package dependencies.

.travis.yml, CHANGELOG.md, package.json, src/js/index.js
- Removed redundant Javascript object wrapper.
- Tidied up link npm scripts.
- Updated Travis config.
=> Removed redundant Javascript object wrapper.

CHANGELOG.md, package.json, src/scss/index.scss
=> v0.9.0 — Updated icons styles.

CHANGELOG.md, package.json, src/scss/index.scss
=> v0.10.0 — Updated footer styles.

CHANGELOG.md, package.json, src/scss/index.scss
=> Updated footer styles.

CHANGELOG.md, package.json
=> Fixed copy assets path.

CHANGELOG.md, package.json
- Fixed `"files"` values in `package.json`.
=> Fixed "files" values in package.json.

.travis.yml, CHANGELOG.md, dangerfile.js, package.json, yarn.lock
- `dangerfile.js` added to check PRs via Travis
- Updated `gulp-build-fozzie` and `fozzie-colour-palette` versions
=> v0.15.0 - Adding dangerfile.js to project and updating packages

CHANGELOG.md, package.json, src/templates/resources/footer-docs-data.json, yarn.lock
- Switched footer docs JSON language to english.
=> v1.1.0 — Switched footer docs JSON language to english.

CHANGELOG.md, package.json, src/templates/resources/footer.json
- addition of `en-` alt text for social icons
=> v1.2.0 - addition of `en-` alt text for social icons

CHANGELOG.md, package.json, src/templates/resources/footer.json
https://jira.just-eat.net/browse/WH-54
Fix invalid links/text in footer links.
This is just a data/ content change.
n/a
=> Fix incorrect footer links.

CHANGELOG.md, package.json, src/js/index.js, src/scss/index.scss, src/templates/footer/index.hbs, src/templates/footer/partials/site-navigation-links.hbs, yarn.lock
- Change styles and js to use collapsible footer links panels on tablets
- Update `fozzie`, `fozzie-colour-pallete` and `gulp-build-fozzie` versions
Before:
After:
=> v1.14.0 collapsible footer links panels on tablets

CHANGELOG.md, package.json, src/templates/resources/footer.json
=> v1.17.0 Remove 'Suggest A Restaurant' link (UK)

CHANGELOG.md, package.json, src/templates/resources/footer.json
Add "Become a courier" link to the about list in the JSON data
=> Add courier link

CHANGELOG.md, package.json, src/templates/resources/footer.json
Fix the broken Iphone and Android play store links
https://jira.just-eat.net/browse/PI-6138
=> Wh 1588 incorrect values in app download links

CHANGELOG.md, package.json, yarn.lock
- Package dependencies.
- Fixed versions of marked and fstream to fix security alerts.
=> v1.23.0 Updates package dependencies

CHANGELOG.md, package.json, src/templates/resources/footer.json
DNMY - For UK Gift Cards release
=> v1.20.1 - GIFT-66 added gift cards links

CHANGELOG.md, package.json, src/templates/resources/footer.json
_**Footer.json** update menulog footer link for **locations** and **cuisines** sections_
=> MCC-1452 update menulog footer link for locations and cuisines

CHANGELOG.md, package.json, src/templates/resources/footer.json
* Update config file
* Update Menulog footer links
=> MCC-1560 update Menulog footer url

.travis.yml, CHANGELOG.md, package.json, yarn.lock
- Updating ML brand to new JET colour palette.
=> v1.26.0 – Updating colour scheme for ML to JET scheme

CHANGELOG.md, package.json, src/scss/index.scss, yarn.lock
- Updated `fozzie-colour-palette` and `fozzie` to apply new JET colour scheme to all countries.
=> v1.27.0 – Updating colour scheme to new JET theme for all countries

CHANGELOG.md, package.json, src/templates/resources/footer.json
- Updated Modern Slavery link.
- Alt text for social links.
- Privacy policy, cookie policy and Terms and conditions links to avoid redirects
- References of `just-eat.ca` to `skipthedishes.com`.
- `en-CA` and `fr-CA` translations.
- Google Plus references.
- Dead links.
=> v1.28.0 - Update Modern Slavery statement

CHANGELOG.md, package.json, src/scss/index.scss, yarn.lock
- Updated to latest font sizes and variables using fozzie `v4`.
=> v1.32.0 – Updating typography variables and fozzie package refs

CHANGELOG.md, package.json, src/scss/index.scss, src/templates/footer/partials/country-selector.hbs, src/templates/resources/footer-docs-data.json, src/templates/resources/footer.json
- New countries to country selector
- New huawei app link
- Modern slavery statement link
-Old commented out code from country selector
=> v1.33.0 - new countries and new huawei app link

CHANGELOG.md, package.json, src/templates/resources/footer.json
- New 'Prensa' link under 'Sobre nostros' for ES footer
=> v1.35.0 - new link for ES

CHANGELOG.md, package.json, src/templates/resources/footer.json
v1.36.0
------------------------------
*May 13, 2021*
- brand links in the IT footer
=> v1.35.0 - Added brand links in the IT footer

CHANGELOG.md, package.json, src/templates/resources/footer.json
v1.37.0
------------------------------
*June 9, 2021*
- “Just Eat for Business” link to the bottom of the “Get to know us” column for the UK.
=> v1.37.0 - Added “Just Eat for Business” link

CHANGELOG.md, package.json, src/templates/resources/footer.json
- "Deliver with Just Eat" link
=> v.1.38.0 - change deliver with just eat link

CHANGELOG.md, package.json, src/templates/resources/footer.json
Updates to "About us" and "Brand" links
=> f-footer@1.39.0 - Update various links.

CHANGELOG.md, package.json, src/templates/resources/footer.json
Update ‘Diventa un Rider’ (Become a rider) link URL
=> f-footer@1.40.0 - update become a rider link.

CHANGELOG.md, package.json, src/templates/resources/footer.json
=> f-footer@v1.41.0 - SEO updates to brand links.

CHANGELOG.md, package.json, src/scss/index.scss, src/scss/partials/_countrySelector.scss, yarn.lock
- Updating to use the new PIE design tokens in fozzie v5.
=> v1.42.0 – Updating to fozzie v5

CHANGELOG.md, package.json, yarn.lock
v1.43.0
------------------------------
*August 27, 2021*
- Updating legacy component to be compatible with Fozzie v6.
=> f-footer@1.43.0 - Update fozzie to v6 beta

CHANGELOG.md, package.json
v1.43.1
------------------------------
*August 31, 2021*
- `package.json` version.
=> f-footer@1.43.1 - Updating package.json version.

CHANGELOG.md, package.json, src/templates/resources/footer.json
Add gender pay gap report link for the UK
=> f-footer@v1.43.2 - Add gender pay gap report link.
