justeat/f-footer

CHANGELOG.md
package.json

- Added `"files"` property to `package.json` to explicitly state which files should be published.

0.14.0 — Added files property to package.json to explicitly state which files should be published.

---

CHANGELOG.md
package.json
src/templates/resources/footer.json

This PR adds pseudo-localised English for `qps-ploc` to allow localisation testing on Windows ([docs](https://docs.microsoft.com/en-us/windows/desktop/intl/using-pseudo-locales-for-localization-testing)).
Values were generated using my custom fork of [anderskaplan/Pseudolocalizer](https://github.com/anderskaplan/Pseudolocalizer):
https://github.com/martincostello/Pseudolocalizer/tree/xliff-support

v1.0.1 - Add qps-ploc resources

---

CHANGELOG.md
package.json
src/scss/index.scss

- fix direction of chevrons in `c-footer-panel`
The direction of the closed / open chevron was backwards - assuming from an icon update(?) maybe.
Before:
After:

v1.3.0 - fix direction of chevrons in `c-footer-panel`

---

CHANGELOG.md
package.json
src/templates/resources/footer-docs-data.json

Fixed currentCountryFlagIconUrl to match GB flag
Before:
After:

v1.3.1 Fixed currentCountryFlagIconUrl to match GB flag

---

.babelrc
.travis.yml
CHANGELOG.md
package.json
yarn.lock

- Upgraded to babel 7.
- Updated module dependencies.
- Travis uses node v8 & v10 to run builds.
- Travis build fixed by regenerating the yarn lock file.
- Lint parsing error fixed by adding "espree" resolution.

v1.4.0 - package dependency updates

---

CHANGELOG.md
package.json
src/js/index.js
src/js/test/index.test.js
src/scss/index.scss
yarn.lock

- Switched `kickoff-utils` package for the `@justeat/f-utils` package (SCSS helpers).
- Updated `fozzie` and `fozzie-colour-palette` versions so Menulog theming cascades into `f-footer`.
- Minor package updates.
- Babel 7 dependencies removed from `package.json` (as now installed as part of `gulp-build-fozzie`).

v1.5.0 – Package updates and menulog theming checks

---

CHANGELOG.md
package.json
src/templates/resources/footer.json

1. Add missing Spanish translations for the feedback text (taken from Spanish homepage).
1. Update the URL for the Just Eat Shop in Ireland to use HTTPS instead of HTTP.

v1.6.0 - Add missing Spanish text

---

CHANGELOG.md
package.json
src/templates/footer/partials/apps-and-social-links.hbs
src/templates/footer/partials/country-selector.hbs
src/templates/footer/partials/je-svg-sprite.hbs
src/templates/footer/partials/payment-provider-links.hbs
src/templates/footer/partials/site-navigation-links.hbs
src/templates/resources/footer-docs-data.json
src/templates/resources/footer.json

Replace existing footer icons rendering with svg sprite. Apps and payment methods icons left because some of them have gradient which doesn't work properly in svg sprite.

v1.8.0 Footer icons optimization via svg sprite

---

CHANGELOG.md
package.json
src/templates/footer/partials/apps-and-social-links.hbs
src/templates/footer/partials/country-selector.hbs
src/templates/footer/partials/site-navigation-links.hbs
src/templates/resources/footer-docs-data.json
yarn.lock

- Temporarily roll back svg sprite change to footer icons to fix WH-692.
This version needs WebBoilerplate >= v1.0.78
- Babel resolution set to fix JS unit tests.

v1.9.0 - rollback svg sprite change to f-footer

---

CHANGELOG.md
package.json
src/templates/resources/footer.json

Adding a "Become a Driver" ("Diventa un Rider") footer link to the Italy tenant.

v1.9.1 - Adding a "Become a Driver" footer link for Italy.

---

.travis.yml
CHANGELOG.md
jest.setup.js
package.json
src/js/test/index.test.js
yarn.lock

Fixes #71.
- Using `concurrently` to run npm scripts concurrently...!
- Call Jest directly from npm scripts to avoid failed test runs exiting with 0 code.
- `matchMedia` mock updated in jest setup file to allow us to modify the `matches` function return value in the unit tests.
- Unit tests explicitly state `matchMedia.matches` return value.
- `matchMedia.matches` setup moved into a separate function.
- Upgraded yarn dependencies.
- Updated Travis config.
- `test` task run as part of `prepare` rather than `lint` task.

v1.10.0 — Fixing up unit tests.

---

CHANGELOG.md
package.json
src/templates/resources/footer-docs-data.json
src/templates/resources/footer.json

https://jira.just-eat.net/browse/MCC-752
NON - CONSUMER WEB | Only show the payment methods offered by Menulog (platform/tenant) in the website footer
- Amex icon (not SafeKey) link in resource json file
- Amex icon for AU & NZ footer template json
- Paypal icon for NZ footer template json

Added Amex card icon src, updated payment icons configuration for AU & NZ

---

CHANGELOG.md
package.json
src/templates/resources/footer.json

Updated footer links to point to the new area and cuisine landing pages.
Link updates only, no copy or markup changes.

v1.12.0 - Update footer links

---

CHANGELOG.md
package.json
src/templates/resources/footer.json

Now the new pages are available on the beta site, we can update the footer links to point to them.
Changing urls in the config file, so it shouldn't be browser-dependent.

v1.15.0 - Use latest links for popular cuisines and locations

---

CHANGELOG.md
package.json
src/templates/footer/partials/site-navigation-links.hbs
src/templates/resources/footer.json

Adding `rel="nofollow"` to login link this so that Google bot doesn't try and crawl the login page.
_Only added one attribute so no accessibility/UI concerns, but HTML has been checked and has not affected page validity._

v1.16.0 - Add `rel="nofollow"` to login link

---

CHANGELOG.md
package.json
src/templates/footer/partials/country-selector.hbs
src/templates/resources/footer.json

Fixed the content of the country selectors for Australia and New Zealand.
Updated some of the old http links.

v1.19.0 - Updated AU/NZ country selector and some other links

---

CHANGELOG.md
package.json
src/templates/footer/partials/country-selector.hbs

Adding another `data-test-id` for... testing purposes.

v1.19.1 - Add another data-test-id

---

.gitignore
CHANGELOG.md
package.json
src/templates/footer/partials/site-navigation-links.hbs
src/templates/resources/footer.json

1. This PR updates the links in the footer for Australia, New Zealand Spain and Italy - the first wave of new HomeWeb tenants.
2. It introduces a new brands column which shows up for Australia. It is conditionally rendered based on whether any brands have been configured for the tenant.
3. It involves removing a grid css class from the footer columns so that flex display correctly assumes the right widths based on how many are rendered.
**I intend to add system tests to HomeWeb which validate the brand logic, as this repository does not look like it is setup for Handlebars tests, and within the next month we hopefully will phase out this repo - so I don't want to spend ages updating it.**
- [-] This PR has been checked with regard to our brand guidelines
- [-] UI Documentation has been …

v1.20.0 Update footer content for Australia, New Zealand, Spain and Italy

---

CHANGELOG.md
package.json
src/templates/resources/footer.json

Remove careers link for Australia, the new pages are not yet ready. Once they are, they can be either re-added here or added to the global footer.

v1.25.0 - Remove careers link for AU

---

CHANGELOG.md
package.json
src/templates/resources/footer.json

This is an update in the resource data for the URL associated with the "Diverenta un Rider" link for Italy. No UI changes required.

v1.25.1 - Update the Diverenta un Rider link in Italy

---

CHANGELOG.md
package.json
src/templates/resources/footer.json

Update footer links/texts in **footer.json** file. No UI change involved.

v1.25.4: update footer links for AU Menulog

---

CHANGELOG.md
package.json
src/templates/resources/footer.json

* Fix URLs for Android and iOS apps (they didn't work at all).
* Remove Microsoft app (it is no longer available).

v1.25.5: Fix Danish app download links

---

CHANGELOG.md
package.json
yarn.lock

- Updated `fozzie` and `fozzie-colour-palette` to pull in new brand colours (Rebrand Phase 3.1).

v1.29.0 - Updating brand colours (rebrand phase 3.1)

---

CHANGELOG.md
package.json
yarn.lock

- Updated `fozzie` and `fozzie-colour-palette` to pull in grey alias updates.

v1.30.0 - Updating grey aliases from fozzie-colour-palette

---

CHANGELOG.md
package.json
src/scss/index.scss
src/scss/partials/_countrySelector.scss

- Use darker greys for background, border and icon colours.
- Small visual issue with the border below the lists.
---
---
---

v1.31.0 - Use latest greys to match Vue footer
